name: Release

# Déclenche la workflow lorsqu'un tag est créé sur une release
on:
  push:
    tags:
      - '*'

# Les étapes de la workflow
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Récupère le code source du repository GitHub
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Release
        uses: goreleaser/goreleaser-action@v4
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Construit l'image Docker à partir du Dockerfile et la pousse vers Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Utilise le tag de la release comme tag pour l'image Docker
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/super_calculator:${{  github.ref_name }}